project_id = "kdszxexyefsbssfhnwxc"

[functions.parse-order]
verify_jwt = true

[functions.import-email]
verify_jwt = true

[functions.send-follow-up]
verify_jwt = true

[functions.create-order]
verify_jwt = false
