/**
 * Zebra Programming Language (ZPL) Generator Utility
 * Generates ZPL strings for a 10x15cm (4x6 inch) thermal label.
 */
import { DEFAULT_COMPANY } from "@/lib/companyConfig";

interface ZplLabelParams {
  orderNumber: string;
  pieceNumber: number;
  totalPieces: number;
  pickup: string;
  delivery: string;
  weight: number;
  quantity: number;
  unit: string;
  sscc?: string;
  qrUrl?: string;
  requirements?: string[];
}

export function generateZplLabel(params: ZplLabelParams): string {
  const {
    orderNumber,
    pieceNumber,
    totalPieces,
    pickup,
    delivery,
    weight,
    quantity,
    unit,
    sscc,
    qrUrl,
    requirements = []
  } = params;

  const isADR = requirements.some(r => r.toUpperCase().includes("ADR"));
  const isKoel = requirements.some(r => r.toUpperCase().includes("KOELING"));

  // ZPL Boilerplate: ^XA (start), ^XZ (end)
  // ^CF0,60 (font)
  // ^FO50,50 (field origin)
  // ^FDtext^FS (field data)
  
  return `^XA
^FX Header
^CF0,60
^FO50,50^FD${DEFAULT_COMPANY.name}^FS
^CF0,30
^FO600,50^FDPiece ${pieceNumber}/${totalPieces}^FS
^FO50,120^GB700,2,2^FS

^FX Order Number
^CF0,40
^FO50,150^FDOrder: #${orderNumber}^FS

^FX QR Code
${qrUrl ? `^FO550,150^BQN,2,4^FDQA,${qrUrl}^FS` : ""}

^FX Cargo Info
^CF0,30
^FO50,220^FDQuantity: ${quantity} ${unit}^FS
^FO50,260^FDWeight: ${weight} kg^FS

^FX Addresses
^CF0,30
^FO50,320^FDORIGIN (FROM):^FS
^CF0,25
^FO70,360^FB600,2,0,L^FD${pickup}^FS

^CF0,30
^FO50,450^FDDESTINATION (TO):^FS
^CF0,40
^FO70,490^FB600,2,0,L^FD${delivery}^FS

^FX Symbols
${isADR ? "^FO550,400^GFA,72,72,6,,K04,K0C,K0E,K0E,K04,^FS^FO600,400^FDADR^FS" : ""}
${isKoel ? "^FO550,450^GFA,72,72,6,,K04,K0C,K0E,K0E,K04,^FS^FO600,450^FDKOEL^FS" : ""}

^FX Barcode SSCC-18
${sscc ? `
^FO100,750^BY3,3,100
^BCN,100,Y,N,N
^FD(00)${sscc}^FS
` : ""}

^FX Footer
^CF0,20
^FO200,1150^FDAuto-generated by OrderFlow TMS^FS
^XZ`;
}
