// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL ?? "").trim();
const SUPABASE_PUBLISHABLE_KEY = String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "").trim();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseGlobal = globalThis as typeof globalThis & {
  __orderflowSupabaseClient?: SupabaseClient<Database>;
};

export const supabase =
  supabaseGlobal.__orderflowSupabaseClient ??
  (supabaseGlobal.__orderflowSupabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }));
